In [2]:
import numpy as np

THE BASICS

In [ ]:
a = np.array([1, 2, 3])
print(a)

In [ ]:

b = np.array([[9, 2, 3], [1, 2, 3], [4, 5, 6]])
print(b)

In [ ]:
# Finding the dimension of a numpy array
print (f"Dimension of array 'a' is {a.ndim}")
print (f"Dimension of array 'b' is {b.ndim}")

# If we want in more detail, the number of rows and columns :-

print (f"Dimension of array 'a' is {a.shape}")
print (f"Dimension of array 'b' is {b.shape}")

# OUTPUT :-
# Dimension of array 'a' is 1
# Dimension of array 'b' is 2
# Dimension of array 'a' is (3,)
# Dimension of array 'b' is (3, 3)



In [24]:
# To access the ij'th element of a numpy array, we use the notation :- a[i, j]

print(f"The element in b_21 is {b[2, 1]} "+ ". Note that the indexing starts as [0, 0]")

# To access a specific row, we use a[rows, columns]:- 
#b[ 0:2 , 0:1 ]
#b[ : , 2: ]
b[ : , 1 ]



The element in b_21 is 5 . Note that the indexing starts as [0, 0]


array([2, 2, 5])

Initializing Different Types of Arrays

In [27]:
# All 0's / 1's matrix
c0 = np.zeros(5) 
c1 = np.ones(5)
print(c0)

d0 = np.zeros((2,3))
d1 = np.ones((2,3))
print(d0)

# Initializing a 3D array
e0 = np.zeros((2, 3, 3))
e1 = np.ones((2, 3, 3))
print(e0)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
# Initializing with another number , say x = 99

# Use np.full((shape), x)

f = np.full((2, 3), 99)

# Initializing an array with shape similar to an already initialized array (a), but with different value 

# Use np.full_like(a, x)

g = np.full_like(a, 4)

# OR :-

h = np.full(a.shape, 4)

In [31]:
# Initializing with random numbers between 0 and 1

np.random.rand(4, 2)

# Initializing an array with shape similar to an already initialized array (a), but with different value 

np.random.random_sample(a.shape)

# Random integer values between x = -1 and y = 5 (not including)

np.random.randint(-1, 5, size = (3, 3))


array([[4, 3, 3],
       [3, 4, 1],
       [4, 3, 4]])

In [32]:
# Initializing the identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# If you have a matrix [1, 2, 3], and you want to stack maultiple copies of it on top of eachother to get 
# [[1, 2, 3]
#   [1, 2, 3]
#   [1, 2, 3]]

arr = np.array([[1, 2, 3]])  # Ensuring it is a 2D array
r1 = np.repeat(arr, 3, axis = 0)

print(r1)

The 0th axis in a 2D array refers to the axis that runs along the rows, and operations along this axis typically aggregate or transform data column-wise.

In [44]:
# Exercise :-
x = np.ones((5, 5))
x[1:4, 1:4] = 0
x[2, 2] = 9
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
# We need to be careful when copying arrays :-

a = np.array([1, 2, 3])
b = a
b[0] = 100
print(a)
print(b)

# Now only b's element should become 100
# But turns out even a's element gets changed to 100, because in numpy both 'a' and the 'b' variable's point to the same array 

a = np.array([1, 2, 3])
b = a.copy()
# Now we are safe, 'a' remains the same
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]
[1 2 3]
[100   2   3]


MATH CAPABALITIES OF NUMPY

In [48]:
# Element wise operations :-
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])

np.array([1, 2, 3, 4])
print(f"{a - 2}")
print(f"{a * 2}")
print(f"{a / 2}")
print(f"{a ** 2}")

# Between 2 arrays :-

print(f"{a + b}")

# Taking trigonometric function on arrays :-
print(f"{np.sin(a)}")
print(f"{np.cos(a)}")


[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


LINEAR ALGEBRA

In [53]:
a = np.full((2,3), 1)
print(a)

b = np.full((3,2), 2)
print(b)

# To mulitply the 2 matrices, a*b wont work as the sizes are different

print(np.matmul(a, b))

# To find the determinant of a matric, we use

c = np.identity(3)
print(np.linalg.det(c))

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
[[6 6]
 [6 6]]
1.0


In [ ]:
## Reference docs :- https://docs.scipy.org/doc/numpy/reference/routines/linalg.html

# Determinant
# Trace
# Singular Value Decompostion
# Eigen values
# Matrix norm
# Inverse
# ..., etc

STATISTICS

In [56]:
stats = np.array([[1, 2, 3], 
                  [4, 5, 6]])

np.min(stats)
np.max(stats)

np.min(stats, axis = 0)
np.min(stats, axis = 1)

np.sum(stats) # Sums up all the elements in the array
np.sum(stats, axis = 0)


array([5, 7, 9])

REORGANIZING ARRAYS

In [59]:
# Reshaping an old array into a new size/shape with the same number of elements

before = np.array([[1, 2, 3], [4, 5, 6]])

after = before.reshape((6, 1))
print(after)

after = before.reshape((3, 2))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2]
 [3 4]
 [5 6]]


In [67]:
# Vertically stacking vectors :- The dimension and number of COLOUMNS of each MATRIX should match
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

np.stack([v1, v2, v3])

before = np.array([[1, 2, 3], [4, 5, 6]])
b1 = np.array([[7, 8, 9]])
np.vstack((before,b1))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
# Horizontal stacking :- The dimesnion and number of ROWS in each matrix must match
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### LOADING DATA FROM A FILE

In [74]:
# If the data in your txt file is formatted with new line breaks, then this will work

file_data = np.genfromtxt('data.txt', delimiter= ',')
file_data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

### BOOLEAN INDEXING AND ADVANCED INDEXING

In [81]:
# Returns which all entries of the text file are greater than 50
print(file_data > 50)

print( ~ ((file_data > 50) & (file_data < 100)))

print(file_data[file_data < 50])

# Tells True for a row if there is anybody in that row that is > 50
np.any(file_data > 50, axis = 0)

# Tells True for a row if everybody in that row that is > 50
np.all(file_data > 50, axis = 0)

# We can do the same for columns as well, by just doing axis = 1


[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]
[[False False False False False  True False False False False False False
  False False False False False False]
 [False False False False False  True False  True False False False False
  False False False False False False]
 [False False False False False False False False  True False False False
  False False False False  True  True]]
[ 1. 13. 21. 11.  4.  3. 34.  6.  7.  8.  0.  1.  2.  3.  4.  5.  3. 42.
 12. 33.  4.  6.  4.  3.  4.  5.  6.  7.  0. 11. 12.  1. 22. 33. 11. 11.
  2.  1.  0.  1.  2.  9.  8.  7.  1.]


array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [83]:
# If you wanted the 2nd, 4th and 8th element in a numpy array, we can do

a = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
a[[1, 3, 7]]

# We can even ask the same element again and again
a[[1, 1, 3]]

array(['b', 'b', 'd'], dtype='<U1')

### Check the exercise photo and try it on your own